In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,54]

In [ ]:
arr=np.array(l)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.asarray(l)

array([ 1,  2,  3,  4, 54])

In [ ]:
arr1=np.array([[1,23,3],[3,4,5]])

In [ ]:
arr.ndim

1

In [ ]:
arr1.ndim

2

In [ ]:
arr

array([ 1,  2,  3,  4, 54])

In [ ]:
arr1

array([[ 1, 23,  3],
       [ 3,  4,  5]])

In [ ]:
mat=np.matrix(l)

In [ ]:
np.asanyarray(l)

array([ 1,  2,  3,  4, 54])

In [ ]:
np.asanyarray(mat)

matrix([[ 1,  2,  3,  4, 54]])

In [ ]:
a=arr

In [ ]:
arr[0]=100

In [ ]:
arr

array([100,   2,   3,   4,  54])

In [ ]:
a      #example of sallow copy in thistype we are not creating seperate memory location for assignment but we are pointing the
#same memory  locaton with another variable so any change in arr will reflect in a

array([100,   2,   3,   4,  54])

In [ ]:
b=np.copy(arr)   #example of deep copy here we are creating the seperate memory locaiton for asignment by using the "copy"
#function so changes in b variable are not going to reflect in arr

In [ ]:
b[0]=233

In [ ]:
b

array([233,   2,   3,   4,  54])

In [ ]:
arr

array([100,   2,   3,   4,  54])

In [ ]:
#fromfunction is a inbulit function in numpy wih which we can generate datasets by passing the required fuction or
#conditions as arguments just look at the below example
np.fromfunction(lambda i,j:i==j,(3,3))


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterater=(i*i for i in range(5))

In [ ]:
np.fromiter(iterater,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring("23 24 25 26",sep=" ")

array([23., 24., 25., 26.])

In [ ]:
np.fromstring("23,24,25,26",sep=",")

array([23., 24., 25., 26.])

In [ ]:
#lets understand some of the inbuild functions of numpy
arr.ndim

1

In [ ]:
arr.size

5

In [ ]:
arr1.size

6

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr.shape

(5,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(0.4,10.4))   #range funcation can only be operated on integer type data

TypeError: ignored

In [ ]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,10,base=2) #frist 2 entries are for start and stop points nxt is for number of iterations u want nxt base

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(1)

array([1.])

In [ ]:
sumen=np.ones((3,4))

In [ ]:
sumen+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
sumen*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.eye(5)  #for generating identy matrix we use eye function

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(2,3)  #rand function generates data with general average and any standard deviation

array([[0.3845665 , 0.99445238, 0.35673365],
       [0.59520292, 0.16403834, 0.40358303]])

In [ ]:
np.random.randn(2,3)  #randn functon is used to generate data with average =0 and std deviation =1

array([[-1.19478126, -0.56741777,  1.6434002 ],
       [ 0.23101968, -0.28755509, -0.47414767]])

In [ ]:
arr2=np.random.randint(1,5,(3,4))

In [ ]:
arr2.size

12

In [ ]:
arr2.reshape(6,2)   #just make sure that number of elements in array before and after reshaping must be same

array([[2, 4],
       [4, 3],
       [2, 2],
       [3, 4],
       [4, 2],
       [1, 3]])

In [ ]:
arr3=np.random.randint(1,3,(5,6))

In [ ]:
arr3

array([[1, 2, 2, 1, 1, 1],
       [1, 1, 2, 1, 1, 2],
       [2, 1, 1, 1, 1, 1],
       [1, 2, 1, 1, 2, 1],
       [2, 1, 1, 1, 2, 1]])

In [ ]:
#to extract any data from the array we use the following terminaology frist we will eneter start and end of rows seperated
#by : and then we will enter[upto which column we want to extact here]
arr3[0,[1,3]]

array([2, 1])

In [ ]:
arr3[2:4,[2,3]]

array([[1, 1],
       [1, 1]])

In [ ]:
arr4= np.random.randint(1,4,(3,3))
arr5= np.random.randint(1,4,(3,3))

In [ ]:
#the below given examples are only perforimg the operations based on index but they are not matrix operations
arr4+arr5

array([[3, 4, 3],
       [3, 4, 6],
       [4, 3, 2]])

In [ ]:
arr4*arr5

array([[2, 3, 2],
       [2, 4, 9],
       [4, 2, 1]])

In [ ]:
arr4/arr5

array([[0.5, 3. , 0.5],
       [0.5, 1. , 1. ],
       [1. , 2. , 1. ]])

In [ ]:
harshi=np.zeros((3,3))

In [ ]:
#numpy_bordacsting means applying for every element of the array
harshi+5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
harshi*5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a=np.array([1,2,3])
harshi+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
#but when your going to add two arrays with different column numbers then its going to through erorrs


In [ ]:
#<array name>.T is used to rotate the array by 90 degree in anticlock wise direction

In [ ]:
np.sqrt(arr4)

array([[1.        , 1.73205081, 1.        ],
       [1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.41421356, 1.        ]])

In [ ]:
np.log10(arr4)

array([[0.        , 0.47712125, 0.        ],
       [0.        , 0.30103   , 0.47712125],
       [0.30103   , 0.30103   , 0.        ]])

In [ ]:
np.exp(arr4)

array([[ 2.71828183, 20.08553692,  2.71828183],
       [ 2.71828183,  7.3890561 , 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  2.71828183]])

In [ ]:
np.min(arr4)

1

In [ ]:
np.max(arr4)

3

In [ ]:
#numpy - array manipulations

In [ ]:
arr6=np.random.randint(1,10,(4,4))

In [ ]:
arr6


array([[6, 6, 2, 3],
       [3, 2, 7, 8],
       [9, 4, 2, 6],
       [8, 9, 9, 3]])

In [ ]:
arr6.reshape(8,2)

array([[6, 6],
       [2, 3],
       [3, 2],
       [7, 8],
       [9, 4],
       [2, 6],
       [8, 9],
       [9, 3]])

In [ ]:
arr6.T

array([[6, 3, 9, 8],
       [6, 2, 4, 9],
       [2, 7, 2, 9],
       [3, 8, 6, 3]])

In [ ]:
data=np.array([[1],[2],[3]])

In [ ]:
np.squeeze(data)

array([1, 2, 3])

In [ ]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [ ]:
np.roll(data,2) #the number that we are mentioned indicates to move the every element of the array forwaard by that many times

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Numpy - Binary operations

In [ ]:
arr7=np.random.randint(1,10,(3,4))
arr8=np.random.randint(1,10,(3,4))

arr8


array([[5, 7, 2, 3],
       [8, 8, 8, 1],
       [3, 1, 7, 6]])

In [ ]:
np.concatenate((arr7,arr8))

array([[2, 9, 4, 8],
       [1, 7, 3, 8],
       [1, 5, 6, 7],
       [5, 7, 2, 3],
       [8, 8, 8, 1],
       [3, 1, 7, 6]])

In [ ]:
arr7

array([[1, 4, 3, 3],
       [5, 8, 3, 5],
       [8, 5, 3, 9]])

In [ ]:
arr7*arr8

array([[ 7, 20,  3, 18],
       [40, 64, 15, 10],
       [48,  5, 21, 27]])

In [ ]:
arr7-arr8

array([[-6, -1,  2, -3],
       [-3,  0, -2,  3],
       [ 2,  4, -4,  6]])

In [ ]:
arr7*arr8

array([[ 7, 20,  3, 18],
       [40, 64, 15, 10],
       [48,  5, 21, 27]])

In [ ]:
~arr7

array([[ -2,  -5,  -4,  -4],
       [ -6,  -9,  -4,  -6],
       [ -9,  -6,  -4, -10]])

In [ ]:
arr7

array([[1, 4, 3, 3],
       [5, 8, 3, 5],
       [8, 5, 3, 9]])

In [ ]:
arr7>arr8

array([[False, False,  True, False],
       [False, False, False,  True],
       [ True,  True, False,  True]])

In [ ]:
#Numpy - string operations

In [ ]:
axx=np.array(["sumen",'challa'])

In [ ]:
axx

array(['sumen', 'challa'], dtype='<U6')

In [ ]:
np.char.upper(axx)

array(['SUMEN', 'CHALLA'], dtype='<U6')

In [ ]:
np.char.capitalize(axx)

array(['Sumen', 'Challa'], dtype='<U6')

In [ ]:
np.char.title(axx)

array(['Sumen', 'Challa'], dtype='<U6')

In [ ]:
#numpy - Mathematical operations

In [ ]:
arr7

array([[1, 4, 3, 3],
       [5, 8, 3, 5],
       [8, 5, 3, 9]])

In [ ]:
np.sin(arr7)  #just remember that we are giving the values in radians not in degrees

array([[ 0.84147098, -0.7568025 ,  0.14112001,  0.14112001],
       [-0.95892427,  0.98935825,  0.14112001, -0.95892427],
       [ 0.98935825, -0.95892427,  0.14112001,  0.41211849]])

In [ ]:
np.cos(arr7)

array([[ 0.54030231, -0.65364362, -0.9899925 , -0.9899925 ],
       [ 0.28366219, -0.14550003, -0.9899925 ,  0.28366219],
       [-0.14550003,  0.28366219, -0.9899925 , -0.91113026]])

In [ ]:
np.median(arr7)

4.5

In [ ]:
np.std(arr7)

2.3496453633119474

In [ ]:
np.var(arr7)

5.520833333333333

In [ ]:
np.min(arr7)

1

In [ ]:
np.max(arr7)

9

In [ ]:
#Numpy - Athematic Operatons

In [ ]:
np.subtract(arr7,arr8)

array([[-6, -1,  2, -3],
       [-3,  0, -2,  3],
       [ 2,  4, -4,  6]])

In [ ]:
np.multiply(arr7,arr8)

array([[ 7, 20,  3, 18],
       [40, 64, 15, 10],
       [48,  5, 21, 27]])

In [ ]:
np.mod(arr7,arr8)      #mod function is used to get the remainder when respective elements of arrays were divided eachother

array([[1, 4, 0, 3],
       [5, 0, 3, 1],
       [2, 0, 3, 0]])

In [ ]:
np.power(arr7,arr8)

array([[       1,     1024,        3,      729],
       [  390625, 16777216,      243,       25],
       [  262144,        5,     2187,      729]])

In [ ]:
np.sqrt(arr7)

array([[1.        , 2.        , 1.73205081, 1.73205081],
       [2.23606798, 2.82842712, 1.73205081, 2.23606798],
       [2.82842712, 2.23606798, 1.73205081, 3.        ]])

In [ ]:
# sorting,searching & count functions in numpy

In [ ]:
ass=np.array([12,109,5,9,13,54,6])

In [ ]:
np.sort(ass)

array([  5,   6,   9,  12,  13,  54, 109])

In [ ]:
np.searchsorted(ass,7) #this inbuit function gives the idea when u search for a element which is not present in it
#and its going to return th index if search is present in the array

0

In [ ]:
np.flip(ass)

array([  6,  54,  13,   9,   5, 109,  12])

In [ ]:
np.count_nonzero(ass)

7

In [ ]:
np.where(ass>11)

(array([0, 1, 4, 5]),)

In [ ]:
np.extract(ass>9,ass)

array([ 12, 109,  13,  54])

In [ ]:
#Numpy - Matrix Library

In [ ]:

import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#we have all the funcions related to matrices in numpy module we just have to go through all of tose things